# Generated by Django 2.2.12 on 2020-11-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201102_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Medicine', 'Medicine'), ('Pediatric', 'Pediatric'), ('Obstetrics and Gynecolgy', 'Obstetrics and Gynecolgy')], max_length=100),
        ),
    ]
